//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayMgtSys.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public decimal NoOfLeaves { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> NetPay { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
